contentColumnType: text
fieldGroup: 834cfea1-d505-43dd-a67e-c817f819ed49
handle: contactPageLabel
instructions: ''
name: 'Contact Page Label'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
