contentColumnType: string
fieldGroup: 834cfea1-d505-43dd-a67e-c817f819ed49
handle: footerButtonLink
instructions: 'Link for the button in the footer.'
name: 'Footer Button Link'
searchable: false
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
