contentColumnType: string
fieldGroup: 834cfea1-d505-43dd-a67e-c817f819ed49
handle: logo
instructions: 'Logo in the header.'
name: Logo
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
    - xml
  defaultUploadLocationSource: 'volume:52993f23-77cb-4b43-bbfc-d10563bc6927'
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:52993f23-77cb-4b43-bbfc-d10563bc6927'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:52993f23-77cb-4b43-bbfc-d10563bc6927'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
