contentColumnType: text
fieldGroup: bc787b3d-4e26-4218-8b29-a30d62f14609
handle: logosSectionTitle
instructions: 'This title will be used for the in-page navigation.'
name: 'Logos Section Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
