contentColumnType: text
fieldGroup: 46bb68c0-9a30-4885-be4c-93df8ce26a0d
handle: processText
instructions: ''
name: 'Process Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
