contentColumnType: text
fieldGroup: 48add524-57f0-4ebd-8d13-9d3dfad696e3
handle: testimonialSliderImageDescription
instructions: 'Text will be displayed below the images.'
name: 'Testimonial Slider Image Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
