contentColumnType: string
fieldGroup: 48add524-57f0-4ebd-8d13-9d3dfad696e3
handle: testimonialSliderImage1
instructions: 'Left image in the right half.'
name: 'Testimonial Slider Image 1'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:52993f23-77cb-4b43-bbfc-d10563bc6927'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:52993f23-77cb-4b43-bbfc-d10563bc6927'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:52993f23-77cb-4b43-bbfc-d10563bc6927'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
