contentColumnType: text
fieldGroup: 346869fd-1445-4aec-a9b0-c6d9505451d3
handle: videoTeaserSectionTitle
instructions: 'This title will be used for the in-page navigation.'
name: 'Video Teaser Section Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
