fieldLayouts:
  efb8b5a5-7457-4b1b-b030-86aa804aa5c8:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: c08975c3-2329-4036-8e3b-5198539b3358
            instructions: ''
            label: ''
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Config'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 480b0543-d870-4ae9-95f7-419f80abb95c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 04024e44-7f35-4690-ac73-d58dd8768e2a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2942cea7-1b11-4112-b894-bec8957044e8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 53863ed7-55fe-4613-b015-a816d9f05355
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ac6ba7de-6f57-46a0-be78-4da49f930f90
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1c77fe9e-c967-4a17-9742-2dea7a7fe3a6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 944c81d7-50f0-4fd2-85b2-dac965b0cac2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Hero
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 95ecac27-759b-48b5-9e22-80d807119826
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ed05e1eb-59db-4cb7-82bc-a938fa9dee71
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4b588541-5cf7-4aed-b335-71f853fb7646
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 89f6bcaf-defe-4bed-81df-4e9d744aca9e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 1e375c5b-04fa-4df7-b1d4-caac52d780dc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 35665684-2b19-4653-896e-b6a9ce4eb278
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 945f0be2-3fdd-4938-8d26-f1ebd4e2ae72
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Video Teaser'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: e8079189-5a62-4a3d-8952-66ccc85deff1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0f96df57-0441-48b2-ac7f-f4960be5385d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 26a89b79-8dd5-4259-8d29-2ca4ca328fb1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 246ec70a-a5f2-4ffa-a08b-d5dae33ba31a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 7d833478-bf99-4751-9849-9b8ce147a892
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Testimonial Slider'
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 2053bbb9-79b0-42c5-8073-ac08d6e548f7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 29e1b7bb-1cd7-432c-9711-a154782865b8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 38a0dc15-21f2-4a77-8c20-5fef6e579a3c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 651b5bbe-4235-4573-9db8-e922727f0f19
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: edceef11-e595-4539-b037-2d866ad7350b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 2fd83d2f-e878-4003-922d-6ad3d8aaaeb0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Logos
        sortOrder: 5
      -
        elements:
          -
            fieldUid: f43b0238-4ea2-40b7-b0c2-85fd9f741740
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ca3cb669-a340-426e-8c9b-6100766e9fd9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 20d08542-1957-48ae-ab8d-1e7b1e2a5733
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a93b48ce-cb73-4718-b035-ab22fdcfa6e0
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 7d1ae3c9-a8e5-4a92-b23d-cdd067a9efb3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: fbd280ee-de1a-46fa-bee7-f976ae6c6c5f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Process
        sortOrder: 6
      -
        elements:
          -
            fieldUid: 5d9e2be2-5bdf-4da4-9cac-9ee204b39413
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 53fd26a8-db82-4a47-a7c5-98f26cb1b7e8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6f13a0e8-feca-46c7-b3cc-6e30f9d09c34
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Team
        sortOrder: 7
handle: home
hasTitleField: false
name: Home
section: dd2d6d7a-3311-4a4b-b9d4-e07553a36d34
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
